apiVersion: v1
kind: Service
metadata:
  name: moveengine
  namespace: kubemove
  labels:
    name: move-engine
spec:
  ports:
  - port: 9000
    name: moveengine
  type: ClusterIP
  selector:
    name: move-engine
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: move-engine
  namespace: kubemove
spec:
  replicas: 1
  selector:
    matchLabels:
      name: move-engine
  template:
    metadata:
      labels:
        name: move-engine
    spec:
      serviceAccountName: kubemove
      containers:
        - name: move-engine
          # Replace this with the built image name
          image: mayankrpatel/move-engine:ci
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubemove"
            - name: GOOGLE_KEY_PATH
              value: /cred/gcp
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /cred/aws-cred
          volumeMounts:
            - name: aws-credentials
              mountPath: /cred
            - name: gcp-credentials
              mountPath: /cred
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credential
        - name: gcp-credentials
          secret:
            secretName: gcp-credential
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: move-pair
  namespace: kubemove
spec:
  replicas: 1
  selector:
    matchLabels:
      name: move-pair
  template:
    metadata:
      labels:
        name: move-pair
    spec:
      serviceAccountName: kubemove
      containers:
        - name: move-pair
          # Replace this with the built image name
          image: mayankrpatel/move-pair:ci
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubemove"
            - name: GOOGLE_KEY_PATH
              value: /cred/gcp
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /cred/aws-cred
          volumeMounts:
            - name: aws-credentials
              mountPath: /cred
            - name: gcp-credentials
              mountPath: /cred
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credential
        - name: gcp-credentials
          secret:
            secretName: gcp-credential
---
apiVersion: v1
kind: Service
metadata:
  name: datasync
  namespace: kubemove
  labels:
    name: move-datasync
spec:
  ports:
  - port: 9000
    name: datasync
  type: ClusterIP
  selector:
    name: move-datasync
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: move-datasync
  namespace: kubemove
spec:
  replicas: 1
  selector:
    matchLabels:
      name: move-datasync
  template:
    metadata:
      labels:
        name: move-datasync
    spec:
      serviceAccountName: kubemove
      containers:
        - name: move-datasync
          # Replace this with the built image name
          image: mayankrpatel/move-ds:ci
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubemove"
