apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubemove
  namespace: kubemove
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubemove
  template:
    metadata:
      labels:
        name: kubemove
    spec:
      serviceAccountName: kubemove
      containers:
        - name: kubemove
          # Replace this with the built image name
          image: mayankrpatel/move-engine:ci
          command:
          - sleep
          - "3600000000000"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubemove"

