apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-plugin
  namespace: kubemove
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-plugin
  template:
    metadata:
      labels:
        name: test-plugin
    spec:
      serviceAccountName: kubemove
      containers:
        - name: test-plugin
          # Replace this with the built image name
          image: mayankrpatel/move-plugin:ci
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVER
              value: "datasync.kubemove.svc,moveengine.kubemove.svc"
            - name: SERVER_PORT
              value: "9000,9000"
            - name: CLIENT
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: OPERATOR_NAME
              value: "kubemove"
