apiVersion: v1
kind: Namespace
metadata:
  name: kubemove

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemove
  namespace: kubemove
  labels:
    component: kubemove

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemove
  labels:
    component: kubemove
subjects:
- kind: ServiceAccount
  name: kubemove
  namespace: kubemove
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
